# Generated by Django 2.2.25 on 2023-01-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuesubcategory',
            options={'verbose_name': 'Issue subcategory'},
        ),
    ]
