# Generated by Django 2.2.25 on 2023-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230129_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solved_by',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='处理人'),
        ),
    ]
